[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.9.0"

[[redirects]]
  from = "/en/tool"
  to = "/en/tool/"
  status = 301

[[redirects]]
  from = "/en/tool/index.html"
  to = "/en/tool/"
  status = 301

[[redirects]]
  from = "/en/blog"
  to = "/en/blog/"
  status = 301

[[redirects]]
  from = "/en/blog/:slug"
  to = "/en/blog/:slug/"
  status = 301

[[redirects]]
  from = "/en/blog/:slug/index.html"
  to = "/en/blog/:slug/"
  status = 301

[[redirects]]
  from = "/en/photo-requirements"
  to = "/en/photo-requirements/"
  status = 301

[[redirects]]
  from = "/en/faq"
  to = "/en/faq/"
  status = 301

[[redirects]]
  from = "/en/updates"
  to = "/en/updates/"
  status = 301

[[redirects]]
  from = "/en/contact"
  to = "/en/contact/"
  status = 301

[[redirects]]
  from = "/en/about"
  to = "/en/about/"
  status = 301

[[redirects]]
  from = "/en/privacy"
  to = "/en/privacy/"
  status = 301

[[redirects]]
  from = "/en/terms"
  to = "/en/terms/"
  status = 301

[[redirects]]
  from = "/en/disclaimer"
  to = "/en/disclaimer/"
  status = 301
